# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"my_beautiful_add_function_from_00_core": "00_core.ipynb",
         "my_beautiful_add_function_2_from_00_core": "00_core.ipynb",
         "my_beautiful_add_function_3_from_00_core": "00_core.ipynb",
         "my_beautiful_add_function_from_Untitled_notebook": "Untitled.ipynb"}

modules = ["core.py",
           "Untitled.py"]

doc_url = "https://hichame.github.io/nbdev_hichame/"

git_url = "https://github.com/hichame/nbdev_hichame/tree/master/"

def custom_doc_links(name): return None
