# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['my_beautiful_add_function_from_00_core', 'my_beautiful_add_function_2_from_00_core',
           'my_beautiful_add_function_3_from_00_core']

# Cell
def my_beautiful_add_function_from_00_core(a, b):
    return a/b




# Cell
def my_beautiful_add_function_2_from_00_core(a, b):
    return a/b

def my_beautiful_add_function_3_from_00_core(a, b):
    return a/b
