# AUTOGENERATED! DO NOT EDIT! File to edit: Untitled.ipynb (unless otherwise specified).

__all__ = ['my_beautiful_add_function_from_Untitled_notebook']

# Cell
def my_beautiful_add_function_from_Untitled_notebook(v, b, m):
    return a/b/m